### ISSUE TITLE
Fails to handle \r on Windows

### ISSUE THREAD

**Issue by ek68794998** [pihvi/yesql#2]
In `.sql` files created on Windows where `\r\n` is the EOL sequence, this script parses the entire file as one query.

Perhaps removing all instances of `\r` from the file before calling `.split()` would be the best solution.

**Comment by pihvi** [comment]
Thanks for the report! Sorry for this late response. Somehow I have missed this issue, but I'll try to fix it now..

**Comment by pihvi** [comment]
This should be now fixed in release 3.2.0. Can you confirm this fixes your case?

**Comment by ek68794998** [comment]
I will take a look ASAP. Thanks.
