### ISSUE TITLE
Throw an error when there is a name conflict

### ISSUE THREAD

**Issue by asafyish** [pihvi/yesql#25]
If I am splitting my queries to multiple files and accidentally gives 2 different queries the exact same name, the last one to load will overwrite the first one, this is a silent fail, I won't even know about it. I think it should throw an error if acc[sqlName] already exist (with the name of the bad query). Can make a PR if you want.

**Comment by pihvi** [comment]
>  Can make a PR if you want.

That would be great!

**Comment by pihvi** [comment]
Available in 5.0.0
